/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Draw;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author Leo
 */
public class Traffic extends javax.swing.JFrame {

    private final int nRed = 10; // sao os tempos, eu acho?
    private final int nYellow = 4;
    private final int nGreen = 10;
    
    private int r, y, g;
    
    private Timer timer;
    
    
    public Traffic() {
        initComponents();
        
        red.setEnabled(true); // come'ca com o vermelho, eu acho?
        yellow.setEnabled(false);
        green.setEnabled(false);
        
        start();
    }
    
    private void start()
    {
        int speed = 1000; // 1s
        
        r = nRed;
        y = nYellow;
        g = nGreen;
        
        
        ActionListener action = new ActionListener(){
            public void actionPerformed(ActionEvent evt)
            {
                if (r >= 0)
                {
                    red.setText(String.valueOf(r));
                    r--;
                }
                else if (y >=0)
                {
                    yellow.setText(String.valueOf(y));
                    y--; 
                    
                    red.setText(null);
                    red.setEnabled(false);
                    yellow.setEnabled(true);
                }
                else if (g >= 0)
                {
                    green.setText(String.valueOf(g));
                    g--;
                    
                    yellow.setText(null);
                    yellow.setEnabled(false);
                    green.setEnabled(true);
                }
                else
                {
                    red.setEnabled(true);
                    yellow.setEnabled(false);
                    green.setEnabled(false);
                    green.setText(null);
                    
                    r = nRed;
                    y = nYellow;
                    g = nGreen;
                }
            }
        };
        
        timer = new Timer(speed, action);
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        red = new javax.swing.JLabel();
        yellow = new javax.swing.JLabel();
        green = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        red.setBackground(new java.awt.Color(0, 0, 0));
        red.setFont(new java.awt.Font("Ebrima", 0, 36)); // NOI18N
        red.setForeground(new java.awt.Color(255, 255, 51));
        red.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Draw/red-80.png"))); // NOI18N
        red.setOpaque(true);

        yellow.setBackground(new java.awt.Color(0, 0, 0));
        yellow.setFont(new java.awt.Font("Ebrima", 0, 36)); // NOI18N
        yellow.setForeground(new java.awt.Color(255, 255, 51));
        yellow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Draw/yellow-80.png"))); // NOI18N
        yellow.setOpaque(true);

        green.setBackground(new java.awt.Color(0, 0, 0));
        green.setFont(new java.awt.Font("Ebrima", 0, 36)); // NOI18N
        green.setForeground(new java.awt.Color(255, 255, 51));
        green.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Draw/green-80.png"))); // NOI18N
        green.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(red, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                    .addComponent(yellow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(green, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(103, 103, 103))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(red, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(yellow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(green, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Traffic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Traffic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Traffic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Traffic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Traffic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel green;
    private javax.swing.JLabel red;
    private javax.swing.JLabel yellow;
    // End of variables declaration//GEN-END:variables
}
